### ISSUE TITLE
Use a mock DNS server to eliminate dependency on netflix

### ISSUE THREAD

**Issue by jcox92** [hudl/fargo#17]
[This test](https://github.com/hudl/fargo/blob/master/dns_discover_test.go#L19) is currently failing because Netflix's discovery test isn't up. That call be mocked out.

**Comment by ryansb** [comment]
The test passes for me. Are you sure it isn't another part of your environment?

**Comment by jcox92** [comment]
Nope, it very well could be. I'll look into it more.
