### ISSUE TITLE
InstanceMetadata with XML API seems not to work

### ISSUE THREAD

**Issue by ryansb** [hudl/fargo#32]
@jerome-laforge you mentioned in #29 that you were having problems with the XML version of instance metadata, can you tell me more about what you're seeing?

**Comment by ryansb** [comment]
Thanks for all that info, I'll try to get to this over the weekend so we have feature parity between the XML and JSON APIs.

**Comment by ryansb** [comment]
@jerome-laforge this should be fixed in #34, so you could pull down that branch if you need it. Sorry for taking so long on this bug.

**Comment by jerome-laforge** [comment]
Many thanks for this fix, I will pull it down and I will check whether
everything is OK. I will send you my feedback before the end of the week.
Many thanks
Best regard

**Comment by jerome-laforge** [comment]
@ryansb I have just finished to test it with eureka 1.1.147 and 1.3.1 and that works like a charm.
Thx.
BR
