### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by sagikazarmark** [hudl/fargo#74]
The last commit in this repo is 5 years old, the last release is even older.

There are a couple outstanding issues and PRs (go modules, updating dependencies, etc) that would be nice to have to keep up with the world.

Do you accept PRs for those things? Or am I better off forking the library?

Thanks!

**Comment by damtur** [comment]
Hello,

We are not actively maintaining it but if you want to file a PR or have any specific PRs you want us to review/merge I'm happy to help.

Thanks!

**Comment by sagikazarmark** [comment]
Thanks for the quick answer @damtur ! I'll open a couple PRs when my time allows.

**Comment by damtur** [comment]
Sure thing 👍🏻
